# Pandas for AI/ML – Conceptual & Technical Assessment

**Name:** Parimala Jyothika Chopparapu  
**Branch:** CSE  
**Batch No:** 2 (2027)  
**Technology Used:** Python, Pandas, VS Code, Jupyter Notebook

## Setup

In [1]:
import numpy as np
import pandas as pd

# Section A – Output Prediction

## Q1. Array Operations and Vectorization

**Question:**

Predict the output of both statements.

Identify one similarity and one difference between the two data structures.

In [2]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64


### Predicted Output

```text
[20 40 60]
0    20
1    40
2    60
dtype: int64
```

### Similarity

Both NumPy arrays and Pandas Series support element-wise multiplication, so multiplying by 2 doubles every value.

### Difference

A NumPy array mainly stores values, while a Pandas Series stores values along with an index.

### Explanation

Multiplication by 2 is applied element-wise to all values in both structures.

## Q2. Boolean Filtering

**Question:**

Predict the rows displayed.

How many rows and columns will the resulting DataFrame contain?

In [3]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90


### Predicted Output

```text
  Student  Marks
1       B     80
2       C     65
3       D     90
```

### Resulting Shape

The resulting DataFrame contains **3 rows and 2 columns**, so its shape is **(3, 2)**.

### Explanation

Boolean filtering selects only the rows where the `Marks` value is greater than or equal to 65.

## Q3. Descriptive statistics

**Question:**

Predict all three outputs.

Explain how the median differs from the mean.

In [4]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

30.0
50
30.0


**Predicted Output:**

30.0  
50  
30.0

**Explanation:**  
The mean is the average of all the values, while the median is the middle value when the data is arranged in order. In this case, both the mean and median are 30.0.

## Q4. Group-wise Analysis

**Question:**

Predict the output.

Explain how `groupby()` calculates the department-wise average.

In [5]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


### Predicted Output

```text
Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64
```

### Explanation

The `groupby()` function groups the data according to the `Department` column and then calculates the mean `Salary` separately for each department.

## Q5. Pandas Correlation - Positive

**Question:**

Predict the correlation coefficient.

Interpret the direction and strength of the relationship.

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


### Predicted Output

```text
1.0
```

### Interpretation

The correlation coefficient of 1.0 indicates a perfect positive relationship between Hours and Marks. As study hours increase, marks also increase proportionally.

### Explanation

The `corr()` function calculates the Pearson correlation coefficient between the two Series.

## Q6. Pandas Correlation - Negative

**Question:**

Predict the correlation coefficient.

Explain what the sign of the coefficient indicates about the relationship.

In [7]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

-1.0


### Predicted Output

```text
-1.0
```

### Explanation

The negative sign indicates an inverse relationship between Price and Demand. As Price increases, Demand decreases. A coefficient of -1.0 represents a perfect negative relationship.

## Section B – Code Correction

### Q1. JSON and CSV

**Question:**

A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code.

In [8]:
import pandas as pd

df = pd.read_csv("students.csv", header=None)
print(df)

     0        1           2      3
0   ID     Name        Date  Marks
1  101  Asha, R  2026-09-01     80
2  102     Ravi  01/09/2026    NaN
3  103     Neha  2026-09-03    NaN


### Issue

The `header=None` argument tells Pandas that the CSV file has no header, so the header row is incorrectly treated as data.

### Corrected Code

In [9]:
import pandas as pd

df = pd.read_csv("students.csv")
print(df)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN


### Explanation

The CSV file already contains column names in its first row. Therefore, we should not use `header=None`. By removing it, Pandas automatically treats the first row as the column headers and reads the remaining rows as student data.

## Q2. Data Analysis

**Question:**

The objective is to display the five highest salaries from a DataFrame. Correct the code.

In [10]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary').head(5))

  Employee  Salary
2        C   25000
0        A   30000
4        E   45000
1        B   50000
3        D   60000


### Issue

The `sort_values('Salary')` function sorts the salaries in ascending order by default. Therefore, `head(5)` selects the five lowest salaries instead of the five highest salaries.

### Corrected Code

In [11]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


### Explanation

The `ascending=False` argument sorts the salaries from highest to lowest. Therefore, `head(5)` returns the five employees with the highest salaries.

### Q3. Cleaning Data

**Question:**

A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.

In [12]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'].fillna(df['Marks'].mean())
print(df)

   Marks
0   70.0
1    NaN
2   90.0


### Issue

The `fillna()` function returns a new Series by default and does not update the original DataFrame. Therefore, the missing value remains `NaN`.

### Corrected Code

In [13]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)

   Marks
0   70.0
1   80.0
2   90.0


### Explanation

The mean of the available marks is 80.0. Using `fillna()` and assigning the result back to the `Marks` column replaces the missing value with the mean and updates the DataFrame.

### Q4. Correct the code to calculate the correlation between Hours and Marks.

**Question:** The objective is to calculate the correlation between Hours and Marks. Correct the code.

import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df.corr('Hours', 'Marks’))


### Issue

The `corr()` method is being called on the whole DataFrame with `Hours` and `Marks` passed as positional arguments. These arguments are not column names for this method, so the code does not calculate the correlation between the two columns as intended.

### Corrected Code

In [14]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


### Explanation

Selecting the `Hours` and `Marks` columns as two Series and using `corr()` calculates the correlation between them. Since the values increase proportionally, the correlation is `1.0`, showing a perfect positive relationship.

## Section C – Edge Cases

### Q1. NumPy Broadcasting

**Question:**

Two NumPy arrays have shapes `(3, 1)` and `(1, 3)`. Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

In [15]:
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


### Predicted Output

```text
[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
```

### Shapes of Arrays

The shape of `a` is **(3, 1)** and the shape of `b` is **(1, 3)**.

### Broadcasting

Broadcasting allows NumPy to perform element-wise operations on arrays with compatible shapes. Here, the dimensions with size `1` are expanded to match the other array. Therefore, the arrays are broadcast to a common shape of **(3, 3)** before addition.

### If `b` is replaced with `np.array([1, 2])`

If `b` is replaced with `np.array([1, 2])`, its shape is **(2,)**. It can be broadcast with `a`, which has shape **(3, 1)**.

The result will have shape **(3, 2)**:

```text
[[11 12]
 [21 22]
 [31 32]]
```

The result is different because the new `b` contains two values, so the resulting array has two columns instead of three.

### Explanation

Broadcasting makes it possible to add arrays with compatible shapes without manually changing their dimensions. Thus, `(3, 1)` and `(1, 3)` produce a `(3, 3)` result, while `(3, 1)` and `(2,)` produce a `(3, 2)` result.

### Q2. CSV Parsing, Missing Values and Dates

**Question:**

A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.

In [16]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)
print(df.dtypes)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN
ID         int64
Name      object
Date      object
Marks    float64
dtype: object


### Quoted Comma

The comma in `"Asha, R"` is inside quotation marks, so Pandas treats it as part of the `Name` value instead of creating an extra column.

### Issues with Date and Marks

The `Date` column contains different date formats, so it should be converted into a consistent date-time format. The `Marks` column contains a blank value and `NA`, which need to be investigated before treating them as missing values.

### Corrected Code

In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv("students.csv", keep_default_na=False)

print("Unique Marks values:", df["Marks"].unique())

df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    errors="coerce",
    dayfirst=True
)

df["Marks"] = df["Marks"].replace("", np.nan)

print(df)
print(df.dtypes)

Unique Marks values: ['80' '' 'NA']
    ID     Name       Date Marks
0  101  Asha, R 2026-09-01    80
1  102     Ravi 2026-09-01   NaN
2  103     Neha 2026-09-03    NA
ID                int64
Name             object
Date     datetime64[ns]
Marks            object
dtype: object


### Explanation

The quoted comma is correctly handled by `read_csv()`, the dates are converted to a common date-time format, and the marks are inspected so that `NA` is not treated as missing without first understanding its meaning.

### Q3. Extreme Salary Value

**Question:**

A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0


### Predicted Output

```text
Mean: 2522500.0
Median: 32500.0
```

### Effect of the Extreme Value

The salary `10000000` is much higher than the other salaries, so it increases the mean significantly. The median is less affected by this extreme value.

### Suitable Statistic

The **median** may better represent a typical employee's salary because it is less affected by the extremely high salary.

### Highest Salary Record

The employee with the highest salary can be identified using `idxmax()`.

In [19]:
highest_salary = df.loc[df["Salary"].idxmax()]

print(highest_salary)

Employee           D
Salary      10000000
Name: 3, dtype: object


### Explanation

The highest salary should be investigated before removing it because it may be a genuine value or a data-entry error, and removing it without checking could affect the accuracy of the analysis.

## Section D – Scenario-Based Questions

### Q1. Student Assessment Data Cleaning

**Question:**

A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing.

### Dataset

The dataset contains student assessment records with inconsistent department names, duplicate records, missing marks, text values in the Marks column, and an invalid mark outside the range of 0–100.

In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_assessment_dirty.csv", sep="\t", keep_default_na=True)

print(df.head())
df.info()
print(df.isnull().sum())

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Student_ID    15 non-null     object
 1   Student_Name  15 non-null     object
 2   Department    15 non-null     object
 3   Assessment    15 non-null     object
 4   Marks         12 non-null     object
dtypes: object(5)
memory usage: 732.0+ bytes
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64


### Standardize Department Names

The department names are standardized so that different forms such as `IT`, `it`, and `I.T.` are represented consistently, and the same approach is applied to `Finance`.

In [21]:
df["Department"] = df["Department"].replace({
    "IT": "IT",
    "it": "IT",
    "I.T.": "IT",
    "Finance": "Finance",
    "finance": "Finance"
})

print(df["Department"].value_counts())

Department
IT         7
HR         4
Finance    4
Name: count, dtype: int64


### Remove Duplicate Records

The dataset contains an exact duplicate student assessment record, so duplicate rows are identified and removed.

In [22]:
duplicates_removed = df.duplicated().sum()

df = df.drop_duplicates()

print("Duplicate records removed:", duplicates_removed)

Duplicate records removed: 1


### Convert Marks to Numeric

The Marks column is first checked to distinguish `Absent`, `NA`, and blank entries. Numeric values and values such as `88 marks` are then converted into numeric form.

In [23]:
df["Mark_Status"] = df["Marks"].astype("string").str.strip()

df["Mark_Status"] = df["Mark_Status"].replace({
    "Absent": "Absent"
}).fillna("Not Entered")

df["Marks"] = pd.to_numeric(
    df["Marks"].astype("string").str.extract(
        r"(\d+(?:\.\d+)?)",
        expand=False
    ),
    errors="coerce"
)

### Handle Missing Marks

Missing marks should be investigated before deleting them. `Absent` and a mark that has not yet been entered may have different meanings, so they should not automatically be treated in the same way.

One risk of deleting missing values without investigating them is that valid information may be lost and the analysis may become biased.

### Identify Invalid Marks

Marks outside the valid range of 0–100 are identified before deciding how to handle them.

In [24]:
invalid_mask = df["Marks"].notna() & ~df["Marks"].between(0, 100)

invalid_marks = df[invalid_mask]

print("Invalid marks:")
print(invalid_marks)

df.loc[invalid_mask, "Mark_Status"] = "Invalid"
df.loc[invalid_mask, "Marks"] = np.nan

Invalid marks:
   Student_ID Student_Name Department Assessment  Marks Mark_Status
14       S114        Kabir    Finance     Python    105         105


### Cleaned DataFrame and Summary

The cleaned DataFrame is displayed along with the number of duplicate records removed, missing marks remaining, and invalid marks identified.

In [25]:
print("Cleaned DataFrame:")
print(df)

print("\nRecords removed:", duplicates_removed)
print(
    "Missing marks remaining:",
    df["Mark_Status"].isin(["Absent", "Not Entered"]).sum()
)
print("Invalid marks identified:", len(invalid_marks))

Cleaned DataFrame:
   Student_ID Student_Name Department Assessment  Marks  Mark_Status
0        S101         Asha         IT     Python     85           85
1        S102         Ravi         IT     Python     78           78
2        S103         Neha         IT     Python     92           92
3        S104        Karan         HR     Python   <NA>  Not Entered
4        S105        Meera         HR     Python   <NA>       Absent
5        S106        Arjun    Finance     Python      0            0
6        S107        Priya    Finance     Python     67           67
7        S108        Rahul         IT     Python     75           75
9        S109        Sneha         IT     Python   <NA>  Not Entered
10       S110        Varun         HR     Python     88     88 marks
11       S111         Diya    Finance     Python     91           91
12       S112         Aman         IT     Python   <NA>  Not Entered
13       S113        Nisha         HR     Python     64           64
14       S114  

### Explanation

The dataset is cleaned by standardizing departments, removing duplicates, distinguishing missing and absent marks, converting marks to numeric values, and identifying invalid marks.